all:hw5

hw5: BinarySearchArray.class Main.class
	java Main	
	
Main.class: Main.java
	javac Main.java
BinarySearchArray.class: BinarySearchArray.java
	javac BinarySearchArray.java
	
	rm -f *.o hw5



