all: clean clear compile run

compile:
	@echo "------------------------------------------"
	@echo "Compiling..."
	@javac Driver.java

run:
	@echo "------------------------------------------"
	@echo "Running..."
	@echo "=========================================="
	@java Driver
	@echo "=========================================="
	@echo "Completed..."

clean:
	@echo "------------------------------------------"
	@echo "Removing Compield Files..."
	@rm -f *.class

clear:
	@clear