all:hw5

hw5: BinaryTree.class Main.class LLHeapTree.class
	java Main	
	
Main.class: Main.java
	javac Main.java
BinaryTree.class: BinaryTree.java
	javac BinaryTree.java
LLHeapTree.class: LLHeapTree.java
	javac LLHeapTree.java
	
	rm -f *.o hw5



