all:hw7

hw7: Driver.class Building.class House.class Office.class Playground.class Market.class Street.class
	java Driver	
	
Driver.class: Driver.java
	javac Driver.java
Building.class: Building.java
	javac Building.java
House.class: House.java
	javac House.java
Office.class: Office.java
	javac Office.java
Playground.class: Playground.java
	javac Playground.java
Market.class: Market.java
	javac Market.java
Street.class: Street.java
	javac Street.java
	
	rm -f *.o hw7



